### PR TITLE
add support for l statements

### PR DESCRIPTION
**Pull request by esromneb**
This PR adds support for l statements (line segments). I've added tests that are as rigorous as the existing tests in the code.

I also fixed a test in your existing code that wasn't properly testing (it required `.bind()`) to work properly.

### CODE REVIEW

**Comment by WesUnwin** [comment]
hi! thanks for PR! Briefly reviewed it - that is indeed useful functionality, also thank you for adding tests, I will likely finish reviewing and merge this PR later today or tomorrow.

**Review by WesUnwin — APPROVED** [review]

**Comment by esromneb** [comment]
Hey no worries, let me know if there's something wrong and I can fix it.

**Comment by WesUnwin** [comment]
PR was merged, and published to npm as version 0.6.0.

However I found a bug, and have fixed it (and published version 0.6.1 as a result).
Objects can be created in two ways, one by using an "o" statement, the other by just starting to define verticies/lines/etc. (the default "untitled" object), in this second case the model needs to be initialized with a lines: [], so have done that.
To avoid duplicated code, have created a new function createNewModel(name) that will ensure models are created in a consistent way, with all the necessary initial properties.

See commit:  https://github.com/WesUnwin/obj-file-parser/commit/1e1249ad6ae5738ba8558f7ffa33c31be3ad1da0

**Comment by esromneb** [comment]
Awesome, thanks for accepting my PR so quickly

**Pull request merged**
